/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.AirEmissionUnit = factory(root.Peidemo.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AirEmissionUnit model module.
   * @module model/AirEmissionUnit
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>AirEmissionUnit</code>.
   * @alias module:model/AirEmissionUnit
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AirEmissionUnit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AirEmissionUnit} obj Optional instance to populate.
   * @return {module:model/AirEmissionUnit} The populated <code>AirEmissionUnit</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('operation'))
        obj.operation = ApiClient.convertToType(data['operation'], 'String');
      if (data.hasOwnProperty('units'))
        obj.units = ApiClient.convertToType(data['units'], 'String');
      if (data.hasOwnProperty('co2'))
        obj.co2 = ApiClient.convertToType(data['co2'], 'Number');
      if (data.hasOwnProperty('nox'))
        obj.nox = ApiClient.convertToType(data['nox'], 'Number');
      if (data.hasOwnProperty('so2'))
        obj.so2 = ApiClient.convertToType(data['so2'], 'Number');
      if (data.hasOwnProperty('hc'))
        obj.hc = ApiClient.convertToType(data['hc'], 'Number');
      if (data.hasOwnProperty('pm'))
        obj.pm = ApiClient.convertToType(data['pm'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} operation
   */
  exports.prototype.operation = undefined;

  /**
   * @member {String} units
   */
  exports.prototype.units = undefined;

  /**
   * @member {Number} co2
   */
  exports.prototype.co2 = undefined;

  /**
   * @member {Number} nox
   */
  exports.prototype.nox = undefined;

  /**
   * @member {Number} so2
   */
  exports.prototype.so2 = undefined;

  /**
   * @member {Number} hc
   */
  exports.prototype.hc = undefined;

  /**
   * @member {Number} pm
   */
  exports.prototype.pm = undefined;

  return exports;

}));
