/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.AtmosphereEmission = factory(root.Peidemo.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AtmosphereEmission model module.
   * @module model/AtmosphereEmission
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>AtmosphereEmission</code>.
   * @alias module:model/AtmosphereEmission
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AtmosphereEmission</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AtmosphereEmission} obj Optional instance to populate.
   * @return {module:model/AtmosphereEmission} The populated <code>AtmosphereEmission</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('engineModel'))
        obj.engineModel = ApiClient.convertToType(data['engineModel'], 'String');
      if (data.hasOwnProperty('fuelType'))
        obj.fuelType = ApiClient.convertToType(data['fuelType'], 'String');
      if (data.hasOwnProperty('mainEnginePower'))
        obj.mainEnginePower = ApiClient.convertToType(data['mainEnginePower'], 'Number');
      if (data.hasOwnProperty('auxiliaryEnginePower'))
        obj.auxiliaryEnginePower = ApiClient.convertToType(data['auxiliaryEnginePower'], 'Number');
      if (data.hasOwnProperty('timeManouvring'))
        obj.timeManouvring = ApiClient.convertToType(data['timeManouvring'], 'Number');
      if (data.hasOwnProperty('timeAtBerth'))
        obj.timeAtBerth = ApiClient.convertToType(data['timeAtBerth'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} engineModel
   */
  exports.prototype.engineModel = undefined;

  /**
   * @member {String} fuelType
   */
  exports.prototype.fuelType = undefined;

  /**
   * @member {Number} mainEnginePower
   */
  exports.prototype.mainEnginePower = undefined;

  /**
   * @member {Number} auxiliaryEnginePower
   */
  exports.prototype.auxiliaryEnginePower = undefined;

  /**
   * @member {Number} timeManouvring
   */
  exports.prototype.timeManouvring = undefined;

  /**
   * @member {Number} timeAtBerth
   */
  exports.prototype.timeAtBerth = undefined;

  return exports;

}));
