/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AtmosphereEmission', 'model/Waste', 'model/WasteWaterEmission'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AtmosphereEmission'), require('./Waste'), require('./WasteWaterEmission'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.Ship = factory(root.Peidemo.ApiClient, root.Peidemo.AtmosphereEmission, root.Peidemo.Waste, root.Peidemo.WasteWaterEmission);
  }
}(this, function(ApiClient, AtmosphereEmission, Waste, WasteWaterEmission) {
  'use strict';

  /**
   * The Ship model module.
   * @module model/Ship
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Ship</code>.
   * @alias module:model/Ship
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Ship</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ship} obj Optional instance to populate.
   * @return {module:model/Ship} The populated <code>Ship</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('vesselName'))
        obj.vesselName = ApiClient.convertToType(data['vesselName'], 'String');
      if (data.hasOwnProperty('imo'))
        obj.imo = ApiClient.convertToType(data['imo'], 'String');
      if (data.hasOwnProperty('vesselType'))
        obj.vesselType = ApiClient.convertToType(data['vesselType'], 'String');
      if (data.hasOwnProperty('vesselCategory'))
        obj.vesselCategory = ApiClient.convertToType(data['vesselCategory'], 'String');
      if (data.hasOwnProperty('grossTonnage'))
        obj.grossTonnage = ApiClient.convertToType(data['grossTonnage'], 'Number');
      if (data.hasOwnProperty('amountCargo'))
        obj.amountCargo = ApiClient.convertToType(data['amountCargo'], 'Number');
      if (data.hasOwnProperty('waste'))
        obj.waste = Waste.constructFromObject(data['waste']);
      if (data.hasOwnProperty('atmosphereEmission'))
        obj.atmosphereEmission = AtmosphereEmission.constructFromObject(data['atmosphereEmission']);
      if (data.hasOwnProperty('wasteWaterEmission'))
        obj.wasteWaterEmission = WasteWaterEmission.constructFromObject(data['wasteWaterEmission']);
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} vesselName
   */
  exports.prototype.vesselName = undefined;

  /**
   * @member {String} imo
   */
  exports.prototype.imo = undefined;

  /**
   * @member {String} vesselType
   */
  exports.prototype.vesselType = undefined;

  /**
   * @member {String} vesselCategory
   */
  exports.prototype.vesselCategory = undefined;

  /**
   * @member {Number} grossTonnage
   */
  exports.prototype.grossTonnage = undefined;

  /**
   * @member {Number} amountCargo
   */
  exports.prototype.amountCargo = undefined;

  /**
   * @member {module:model/Waste} waste
   */
  exports.prototype.waste = undefined;

  /**
   * @member {module:model/AtmosphereEmission} atmosphereEmission
   */
  exports.prototype.atmosphereEmission = undefined;

  /**
   * @member {module:model/WasteWaterEmission} wasteWaterEmission
   */
  exports.prototype.wasteWaterEmission = undefined;

  return exports;

}));
