/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SimulationInput', 'model/SimulationOutput'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SimulationInput'), require('./SimulationOutput'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.Simulation = factory(root.Peidemo.ApiClient, root.Peidemo.SimulationInput, root.Peidemo.SimulationOutput);
  }
}(this, function(ApiClient, SimulationInput, SimulationOutput) {
  'use strict';

  /**
   * The Simulation model module.
   * @module model/Simulation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Simulation</code>.
   * @alias module:model/Simulation
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Simulation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Simulation} obj Optional instance to populate.
   * @return {module:model/Simulation} The populated <code>Simulation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('input'))
        obj.input = SimulationInput.constructFromObject(data['input']);
      if (data.hasOwnProperty('output'))
        obj.output = SimulationOutput.constructFromObject(data['output']);
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {module:model/SimulationInput} input
   */
  exports.prototype.input = undefined;

  /**
   * @member {module:model/SimulationOutput} output
   */
  exports.prototype.output = undefined;

  return exports;

}));
