/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SimulationInputItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SimulationInputItem'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.SimulationInput = factory(root.Peidemo.ApiClient, root.Peidemo.SimulationInputItem);
  }
}(this, function(ApiClient, SimulationInputItem) {
  'use strict';

  /**
   * The SimulationInput model module.
   * @module model/SimulationInput
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>SimulationInput</code>.
   * @alias module:model/SimulationInput
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SimulationInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimulationInput} obj Optional instance to populate.
   * @return {module:model/SimulationInput} The populated <code>SimulationInput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [SimulationInputItem]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/SimulationInputItem>} items
   */
  exports.prototype.items = undefined;

  return exports;

}));
