/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.SimulationInputItem = factory(root.Peidemo.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SimulationInputItem model module.
   * @module model/SimulationInputItem
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>SimulationInputItem</code>.
   * @alias module:model/SimulationInputItem
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SimulationInputItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimulationInputItem} obj Optional instance to populate.
   * @return {module:model/SimulationInputItem} The populated <code>SimulationInputItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('dateStart'))
        obj.dateStart = ApiClient.convertToType(data['dateStart'], 'Number');
      if (data.hasOwnProperty('dateEnd'))
        obj.dateEnd = ApiClient.convertToType(data['dateEnd'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('ships'))
        obj.ships = ApiClient.convertToType(data['ships'], ['String']);
    }
    return obj;
  }

  /**
   * @member {Number} dateStart
   */
  exports.prototype.dateStart = undefined;

  /**
   * @member {Number} dateEnd
   */
  exports.prototype.dateEnd = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Array.<String>} ships
   */
  exports.prototype.ships = undefined;

  return exports;

}));
