/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SimulationOutputItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SimulationOutputItem'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.SimulationOutput = factory(root.Peidemo.ApiClient, root.Peidemo.SimulationOutputItem);
  }
}(this, function(ApiClient, SimulationOutputItem) {
  'use strict';

  /**
   * The SimulationOutput model module.
   * @module model/SimulationOutput
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>SimulationOutput</code>.
   * @alias module:model/SimulationOutput
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SimulationOutput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimulationOutput} obj Optional instance to populate.
   * @return {module:model/SimulationOutput} The populated <code>SimulationOutput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [SimulationOutputItem]);
      if (data.hasOwnProperty('averageOutput'))
        obj.averageOutput = SimulationOutputItem.constructFromObject(data['averageOutput']);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/SimulationOutputItem>} items
   */
  exports.prototype.items = undefined;

  /**
   * @member {module:model/SimulationOutputItem} averageOutput
   */
  exports.prototype.averageOutput = undefined;

  return exports;

}));
