/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.WasteWaterEmission = factory(root.Peidemo.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WasteWaterEmission model module.
   * @module model/WasteWaterEmission
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>WasteWaterEmission</code>.
   * @alias module:model/WasteWaterEmission
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WasteWaterEmission</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WasteWaterEmission} obj Optional instance to populate.
   * @return {module:model/WasteWaterEmission} The populated <code>WasteWaterEmission</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('oilyBilgeWater'))
        obj.oilyBilgeWater = ApiClient.convertToType(data['oilyBilgeWater'], 'Number');
      if (data.hasOwnProperty('oilyResidues'))
        obj.oilyResidues = ApiClient.convertToType(data['oilyResidues'], 'Number');
      if (data.hasOwnProperty('oilyTankWashings'))
        obj.oilyTankWashings = ApiClient.convertToType(data['oilyTankWashings'], 'Number');
      if (data.hasOwnProperty('dirtyBallastWater'))
        obj.dirtyBallastWater = ApiClient.convertToType(data['dirtyBallastWater'], 'Number');
      if (data.hasOwnProperty('scaleAndSludgeTankCleaning'))
        obj.scaleAndSludgeTankCleaning = ApiClient.convertToType(data['scaleAndSludgeTankCleaning'], 'Number');
      if (data.hasOwnProperty('otherOil'))
        obj.otherOil = ApiClient.convertToType(data['otherOil'], 'Number');
      if (data.hasOwnProperty('noxiusLiquidSubstancesX'))
        obj.noxiusLiquidSubstancesX = ApiClient.convertToType(data['noxiusLiquidSubstancesX'], 'Number');
      if (data.hasOwnProperty('nlsY'))
        obj.nlsY = ApiClient.convertToType(data['nlsY'], 'Number');
      if (data.hasOwnProperty('nlsZ'))
        obj.nlsZ = ApiClient.convertToType(data['nlsZ'], 'Number');
      if (data.hasOwnProperty('nlsOther'))
        obj.nlsOther = ApiClient.convertToType(data['nlsOther'], 'Number');
      if (data.hasOwnProperty('sewage'))
        obj.sewage = ApiClient.convertToType(data['sewage'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Number} oilyBilgeWater
   */
  exports.prototype.oilyBilgeWater = undefined;

  /**
   * @member {Number} oilyResidues
   */
  exports.prototype.oilyResidues = undefined;

  /**
   * @member {Number} oilyTankWashings
   */
  exports.prototype.oilyTankWashings = undefined;

  /**
   * @member {Number} dirtyBallastWater
   */
  exports.prototype.dirtyBallastWater = undefined;

  /**
   * @member {Number} scaleAndSludgeTankCleaning
   */
  exports.prototype.scaleAndSludgeTankCleaning = undefined;

  /**
   * @member {Number} otherOil
   */
  exports.prototype.otherOil = undefined;

  /**
   * @member {Number} noxiusLiquidSubstancesX
   */
  exports.prototype.noxiusLiquidSubstancesX = undefined;

  /**
   * @member {Number} nlsY
   */
  exports.prototype.nlsY = undefined;

  /**
   * @member {Number} nlsZ
   */
  exports.prototype.nlsZ = undefined;

  /**
   * @member {Number} nlsOther
   */
  exports.prototype.nlsOther = undefined;

  /**
   * @member {Number} sewage
   */
  exports.prototype.sewage = undefined;

  return exports;

}));
