/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.Waste = factory(root.Peidemo.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Waste model module.
   * @module model/Waste
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Waste</code>.
   * @alias module:model/Waste
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Waste</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Waste} obj Optional instance to populate.
   * @return {module:model/Waste} The populated <code>Waste</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('plastics'))
        obj.plastics = ApiClient.convertToType(data['plastics'], 'Number');
      if (data.hasOwnProperty('foodWaste'))
        obj.foodWaste = ApiClient.convertToType(data['foodWaste'], 'Number');
      if (data.hasOwnProperty('domesticWaste'))
        obj.domesticWaste = ApiClient.convertToType(data['domesticWaste'], 'Number');
      if (data.hasOwnProperty('cookingOil'))
        obj.cookingOil = ApiClient.convertToType(data['cookingOil'], 'Number');
      if (data.hasOwnProperty('incineratorAshes'))
        obj.incineratorAshes = ApiClient.convertToType(data['incineratorAshes'], 'Number');
      if (data.hasOwnProperty('operationalWaste'))
        obj.operationalWaste = ApiClient.convertToType(data['operationalWaste'], 'Number');
      if (data.hasOwnProperty('animalCarcass'))
        obj.animalCarcass = ApiClient.convertToType(data['animalCarcass'], 'Number');
      if (data.hasOwnProperty('fishingGear'))
        obj.fishingGear = ApiClient.convertToType(data['fishingGear'], 'Number');
      if (data.hasOwnProperty('ewaste'))
        obj.ewaste = ApiClient.convertToType(data['ewaste'], 'Number');
      if (data.hasOwnProperty('cargoResiduesHarmful'))
        obj.cargoResiduesHarmful = ApiClient.convertToType(data['cargoResiduesHarmful'], 'Number');
      if (data.hasOwnProperty('cargoResiduesNonHarmful'))
        obj.cargoResiduesNonHarmful = ApiClient.convertToType(data['cargoResiduesNonHarmful'], 'Number');
      if (data.hasOwnProperty('passivelyFishedWasted'))
        obj.passivelyFishedWasted = ApiClient.convertToType(data['passivelyFishedWasted'], 'Number');
      if (data.hasOwnProperty('otherSubstances'))
        obj.otherSubstances = ApiClient.convertToType(data['otherSubstances'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Number} plastics
   */
  exports.prototype.plastics = undefined;

  /**
   * @member {Number} foodWaste
   */
  exports.prototype.foodWaste = undefined;

  /**
   * @member {Number} domesticWaste
   */
  exports.prototype.domesticWaste = undefined;

  /**
   * @member {Number} cookingOil
   */
  exports.prototype.cookingOil = undefined;

  /**
   * @member {Number} incineratorAshes
   */
  exports.prototype.incineratorAshes = undefined;

  /**
   * @member {Number} operationalWaste
   */
  exports.prototype.operationalWaste = undefined;

  /**
   * @member {Number} animalCarcass
   */
  exports.prototype.animalCarcass = undefined;

  /**
   * @member {Number} fishingGear
   */
  exports.prototype.fishingGear = undefined;

  /**
   * @member {Number} ewaste
   */
  exports.prototype.ewaste = undefined;

  /**
   * @member {Number} cargoResiduesHarmful
   */
  exports.prototype.cargoResiduesHarmful = undefined;

  /**
   * @member {Number} cargoResiduesNonHarmful
   */
  exports.prototype.cargoResiduesNonHarmful = undefined;

  /**
   * @member {Number} passivelyFishedWasted
   */
  exports.prototype.passivelyFishedWasted = undefined;

  /**
   * @member {Number} otherSubstances
   */
  exports.prototype.otherSubstances = undefined;

  return exports;

}));
