/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Ekpi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Ekpi'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.EkpiResourceApi = factory(root.Peidemo.ApiClient, root.Peidemo.Ekpi);
  }
}(this, function(ApiClient, Ekpi) {
  'use strict';

  /**
   * EkpiResource service.
   * @module api/EkpiResourceApi
   * @version 0.0.1
   */

  /**
   * Constructs a new EkpiResourceApi. 
   * @alias module:api/EkpiResourceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createEkpi operation.
     * @callback module:api/EkpiResourceApi~createEkpiCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Ekpi} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a Ekpi
     * If id is not provided, it will be randomly generated
     * @param {module:model/Ekpi} body Ekpi description
     * @param {module:api/EkpiResourceApi~createEkpiCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Ekpi}
     */
    this.createEkpi = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createEkpi");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Ekpi;

      return this.apiClient.callApi(
        '/Ekpis/create', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteEkpi operation.
     * @callback module:api/EkpiResourceApi~deleteEkpiCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Ekpi
     * 
     * @param {String} id ID of Ekpi
     * @param {module:api/EkpiResourceApi~deleteEkpiCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteEkpi = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteEkpi");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/Ekpis/delete/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getEkpiByID operation.
     * @callback module:api/EkpiResourceApi~getEkpiByIDCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Ekpi} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a Ekpi by id
     * 
     * @param {String} id Ekpi
     * @param {module:api/EkpiResourceApi~getEkpiByIDCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Ekpi}
     */
    this.getEkpiByID = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getEkpiByID");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Ekpi;

      return this.apiClient.callApi(
        '/Ekpis/get/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listEkpis operation.
     * @callback module:api/EkpiResourceApi~listEkpisCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Ekpi>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all Ekpis
     * 
     * @param {Object} opts Optional parameters
     * @param {String} opts.category category
     * @param {module:api/EkpiResourceApi~listEkpisCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Ekpi>}
     */
    this.listEkpis = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'category': opts['category'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Ekpi];

      return this.apiClient.callApi(
        '/Ekpis/list', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateEkpi operation.
     * @callback module:api/EkpiResourceApi~updateEkpiCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Ekpi} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a Ekpi
     * 
     * @param {module:model/Ekpi} body Ekpi description
     * @param {module:api/EkpiResourceApi~updateEkpiCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Ekpi}
     */
    this.updateEkpi = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateEkpi");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Ekpi;

      return this.apiClient.callApi(
        '/Ekpis/update', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
