/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Ship'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Ship'));
  } else {
    // Browser globals (root is window)
    if (!root.Peidemo) {
      root.Peidemo = {};
    }
    root.Peidemo.ShipResourceApi = factory(root.Peidemo.ApiClient, root.Peidemo.Ship);
  }
}(this, function(ApiClient, Ship) {
  'use strict';

  /**
   * ShipResource service.
   * @module api/ShipResourceApi
   * @version 0.0.1
   */

  /**
   * Constructs a new ShipResourceApi. 
   * @alias module:api/ShipResourceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createShip operation.
     * @callback module:api/ShipResourceApi~createShipCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Ship} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a Ship
     * If id is not provided, it will be randomly generated
     * @param {module:model/Ship} body Ship description
     * @param {module:api/ShipResourceApi~createShipCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Ship}
     */
    this.createShip = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createShip");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Ship;

      return this.apiClient.callApi(
        '/ships/create', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteShip operation.
     * @callback module:api/ShipResourceApi~deleteShipCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Ship
     * 
     * @param {String} id ID of Ship
     * @param {module:api/ShipResourceApi~deleteShipCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteShip = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteShip");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/ships/delete/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getShipByID operation.
     * @callback module:api/ShipResourceApi~getShipByIDCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Ship} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a Ship by id
     * 
     * @param {String} id Ship
     * @param {module:api/ShipResourceApi~getShipByIDCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Ship}
     */
    this.getShipByID = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getShipByID");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Ship;

      return this.apiClient.callApi(
        '/ships/get/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listShips operation.
     * @callback module:api/ShipResourceApi~listShipsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Ship>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all Ships
     * 
     * @param {Object} opts Optional parameters
     * @param {String} opts.category category
     * @param {module:api/ShipResourceApi~listShipsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Ship>}
     */
    this.listShips = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'category': opts['category'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Ship];

      return this.apiClient.callApi(
        '/ships/list', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateShip operation.
     * @callback module:api/ShipResourceApi~updateShipCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Ship} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a Ship
     * 
     * @param {module:model/Ship} body Ship description
     * @param {module:api/ShipResourceApi~updateShipCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Ship}
     */
    this.updateShip = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateShip");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Ship;

      return this.apiClient.callApi(
        '/ships/update', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
