/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Peidemo);
  }
}(this, function(expect, Peidemo) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AirEmission', function() {
      beforeEach(function() {
        instance = new Peidemo.AirEmission();
      });

      it('should create an instance of AirEmission', function() {
        // TODO: update the code to test AirEmission
        expect(instance).to.be.a(Peidemo.AirEmission);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property category (base name: "category")', function() {
        // TODO: update the code to test the property category
        expect(instance).to.have.property('category');
        // expect(instance.category).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property berthBykWh (base name: "berthBykWh")', function() {
        // TODO: update the code to test the property berthBykWh
        expect(instance).to.have.property('berthBykWh');
        // expect(instance.berthBykWh).to.be(expectedValueLiteral);
      });

      it('should have the property manouvringBykWh (base name: "manouvringBykWh")', function() {
        // TODO: update the code to test the property manouvringBykWh
        expect(instance).to.have.property('manouvringBykWh');
        // expect(instance.manouvringBykWh).to.be(expectedValueLiteral);
      });

    });
  });

}));
