/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Peidemo);
  }
}(this, function(expect, Peidemo) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AtmosphereEmission', function() {
      beforeEach(function() {
        instance = new Peidemo.AtmosphereEmission();
      });

      it('should create an instance of AtmosphereEmission', function() {
        // TODO: update the code to test AtmosphereEmission
        expect(instance).to.be.a(Peidemo.AtmosphereEmission);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property engineModel (base name: "engineModel")', function() {
        // TODO: update the code to test the property engineModel
        expect(instance).to.have.property('engineModel');
        // expect(instance.engineModel).to.be(expectedValueLiteral);
      });

      it('should have the property fuelType (base name: "fuelType")', function() {
        // TODO: update the code to test the property fuelType
        expect(instance).to.have.property('fuelType');
        // expect(instance.fuelType).to.be(expectedValueLiteral);
      });

      it('should have the property mainEnginePower (base name: "mainEnginePower")', function() {
        // TODO: update the code to test the property mainEnginePower
        expect(instance).to.have.property('mainEnginePower');
        // expect(instance.mainEnginePower).to.be(expectedValueLiteral);
      });

      it('should have the property auxiliaryEnginePower (base name: "auxiliaryEnginePower")', function() {
        // TODO: update the code to test the property auxiliaryEnginePower
        expect(instance).to.have.property('auxiliaryEnginePower');
        // expect(instance.auxiliaryEnginePower).to.be(expectedValueLiteral);
      });

      it('should have the property timeManouvring (base name: "timeManouvring")', function() {
        // TODO: update the code to test the property timeManouvring
        expect(instance).to.have.property('timeManouvring');
        // expect(instance.timeManouvring).to.be(expectedValueLiteral);
      });

      it('should have the property timeAtBerth (base name: "timeAtBerth")', function() {
        // TODO: update the code to test the property timeAtBerth
        expect(instance).to.have.property('timeAtBerth');
        // expect(instance.timeAtBerth).to.be(expectedValueLiteral);
      });

    });
  });

}));
