/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Peidemo);
  }
}(this, function(expect, Peidemo) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Config', function() {
      beforeEach(function() {
        instance = new Peidemo.Config();
      });

      it('should create an instance of Config', function() {
        // TODO: update the code to test Config
        expect(instance).to.be.a(Peidemo.Config);
      });

      it('should have the property otConfig (base name: "otConfig")', function() {
        // TODO: update the code to test the property otConfig
        expect(instance).to.have.property('otConfig');
        // expect(instance.otConfig).to.be(expectedValueLiteral);
      });

      it('should have the property ihConfig (base name: "ihConfig")', function() {
        // TODO: update the code to test the property ihConfig
        expect(instance).to.have.property('ihConfig');
        // expect(instance.ihConfig).to.be(expectedValueLiteral);
      });

    });
  });

}));
