/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Peidemo);
  }
}(this, function(expect, Peidemo) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SimulationOutputItem', function() {
      beforeEach(function() {
        instance = new Peidemo.SimulationOutputItem();
      });

      it('should create an instance of SimulationOutputItem', function() {
        // TODO: update the code to test SimulationOutputItem
        expect(instance).to.be.a(Peidemo.SimulationOutputItem);
      });

      it('should have the property dateStart (base name: "dateStart")', function() {
        // TODO: update the code to test the property dateStart
        expect(instance).to.have.property('dateStart');
        // expect(instance.dateStart).to.be(expectedValueLiteral);
      });

      it('should have the property dateEnd (base name: "dateEnd")', function() {
        // TODO: update the code to test the property dateEnd
        expect(instance).to.have.property('dateEnd');
        // expect(instance.dateEnd).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property ekpis (base name: "ekpis")', function() {
        // TODO: update the code to test the property ekpis
        expect(instance).to.have.property('ekpis');
        // expect(instance.ekpis).to.be(expectedValueLiteral);
      });

      it('should have the property subindices (base name: "subindices")', function() {
        // TODO: update the code to test the property subindices
        expect(instance).to.have.property('subindices');
        // expect(instance.subindices).to.be(expectedValueLiteral);
      });

      it('should have the property sei (base name: "sei")', function() {
        // TODO: update the code to test the property sei
        expect(instance).to.have.property('sei');
        // expect(instance.sei).to.be(expectedValueLiteral);
      });

    });
  });

}));
