/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Peidemo);
  }
}(this, function(expect, Peidemo) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SimulationOutput', function() {
      beforeEach(function() {
        instance = new Peidemo.SimulationOutput();
      });

      it('should create an instance of SimulationOutput', function() {
        // TODO: update the code to test SimulationOutput
        expect(instance).to.be.a(Peidemo.SimulationOutput);
      });

      it('should have the property items (base name: "items")', function() {
        // TODO: update the code to test the property items
        expect(instance).to.have.property('items');
        // expect(instance.items).to.be(expectedValueLiteral);
      });

      it('should have the property averageOutput (base name: "averageOutput")', function() {
        // TODO: update the code to test the property averageOutput
        expect(instance).to.have.property('averageOutput');
        // expect(instance.averageOutput).to.be(expectedValueLiteral);
      });

    });
  });

}));
