/*
 * PEIDEMO
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Peidemo);
  }
}(this, function(expect, Peidemo) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Peidemo.ConfigResourceApi();
  });

  describe('(package)', function() {
    describe('ConfigResourceApi', function() {
      describe('getConfig', function() {
        it('should call getConfig successfully', function(done) {
          // TODO: uncomment getConfig call and complete the assertions
          /*

          instance.getConfig(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Peidemo.Config);
            expect(data.otConfig).to.be.a(Peidemo.OTConfig);
                  expect(data.otConfig.serviceUrl).to.be.a('string');
              expect(data.otConfig.serviceUrl).to.be("");
              expect(data.otConfig.apiKey).to.be.a('string');
              expect(data.otConfig.apiKey).to.be("");
            expect(data.ihConfig).to.be.a(Peidemo.IHConfig);
                  expect(data.ihConfig.serviceUrl).to.be.a('string');
              expect(data.ihConfig.serviceUrl).to.be("");
              expect(data.ihConfig.apiKey).to.be.a('string');
              expect(data.ihConfig.apiKey).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setConfig', function() {
        it('should call setConfig successfully', function(done) {
          // TODO: uncomment, update parameter values for setConfig call and complete the assertions
          /*
          var body = new Peidemo.Config();
          body.otConfig = new Peidemo.OTConfig();
          body.otConfig.serviceUrl = "";
          body.otConfig.apiKey = "";
          body.ihConfig = new Peidemo.IHConfig();
          body.ihConfig.serviceUrl = "";
          body.ihConfig.apiKey = "";

          instance.setConfig(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Peidemo.Config);
            expect(data.otConfig).to.be.a(Peidemo.OTConfig);
                  expect(data.otConfig.serviceUrl).to.be.a('string');
              expect(data.otConfig.serviceUrl).to.be("");
              expect(data.otConfig.apiKey).to.be.a('string');
              expect(data.otConfig.apiKey).to.be("");
            expect(data.ihConfig).to.be.a(Peidemo.IHConfig);
                  expect(data.ihConfig.serviceUrl).to.be.a('string');
              expect(data.ihConfig.serviceUrl).to.be("");
              expect(data.ihConfig.apiKey).to.be.a('string');
              expect(data.ihConfig.apiKey).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
